import dataScience1 from './dataScience1.png'
import dataScience2 from './dataScience2.jpg'
import dataScience3 from './dataScience3.jpg'
import dataScience4 from './dataScience4.jpg'
import dataScience5 from './dataScience5.jpg'
import softwareEngineering1 from './softwareEngineering1.jpg'
import softwareEngineering2 from './softwareEngineering2.jpg'
import softwareEngineering3 from './softwareEngineering3.jpg'
import softwareEngineering4 from './softwareEngineering4.jpg'
import softwareEngineering5 from './softwareEngineering5.jpg'
import FinanceInvestment1 from './Finance&Investment1.jpg'
import FinanceInvestment2 from './Finance&Investment2.jpg'
import FinanceInvestment3 from './Finance&Investment3.jpg'
import FinanceInvestment4 from './Finance&Investment4.jpg'
import FinanceInvestment5 from './Finance&Investment5.jpg'
import Enterpreneurship1 from './Enterpreneurship1.jpg'
import Enterpreneurship2 from './Enterpreneurship2.jpg'
import Enterpreneurship3 from './Enterpreneurship3.jpg'
import Enterpreneurship4 from './Enterpreneurship4.jpeg'
import Enterpreneurship5 from './Enterpreneurship5.jpg'

export { dataScience1, dataScience2, dataScience3, dataScience4, dataScience5, softwareEngineering1, softwareEngineering2, softwareEngineering3, softwareEngineering4, softwareEngineering5, FinanceInvestment1, FinanceInvestment2, FinanceInvestment3, FinanceInvestment4, FinanceInvestment5, Enterpreneurship1, Enterpreneurship2, Enterpreneurship3, Enterpreneurship4, Enterpreneurship5}